CREATE OR REPLACE FUNCTION INCREMENT_NUM_PAR() RETURNS TRIGGER AS
$$  BEGIN
        UPDATE events 
        SET num_part = num_part + 1
        WHERE events.id = new.p_event;
        RETURN NULL;
    END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER SUBSCRIPTION
AFTER INSERT ON partecipations
FOR EACH ROW
EXECUTE PROCEDURE INCREMENT_NUM_PAR();

CREATE OR REPLACE FUNCTION DECREMENT_NUM_PAR() RETURNS TRIGGER AS
$$  BEGIN
        UPDATE events 
        SET num_part = num_part - 1
        WHERE events.id = old.p_event;
        RETURN NULL;
    END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER DESUBSCRIPTION
AFTER DELETE ON partecipations
FOR EACH ROW
EXECUTE PROCEDURE DECREMENT_NUM_PAR();